name: Initialize Algolia search
on:
  push:
    branches: 'gh-pages'
jobs:
  algolia-search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Cache gems   
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Algolia Jekyll Action
        uses: dieghernan/algolia-jekyll-action@v1
        with:
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
